# General lint configuration
select = ["E", "F", "W", "C90"]

# McCabe complexity settings
[lint.mccabe]
max-complexity = 4
max-function-length = 50
max-method-length = 30
max-class-length = 100
max-module-lines = 200
max-arguments = 2
max-statements = 10
max-nested-blocks = 2
