# General lint configuration
[lint]
select = ["E", "F", "W", "C90"]

# McCabe complexity settings
[lint.mccabe]
max-complexity = 4

# Pylint complexity and design constraints
[lint.pylint]
max-statements = 10   # Limits statements per function (approximates method length)
max-nested-blocks = 2 # Limits nesting depth
max-locals = 5        # Limits local variables
max-public-methods = 5 # Limits public methods per class
max-branches = 3      # Limits branches per function
max-returns = 2       # Limits return statements per function
